package com.zytx.cxf.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 20 17:39:44 CST 2017
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://service.ws.cxf.zytx.com/", name = "JyDataUpdateService")
@XmlSeeAlso({ObjectFactory.class})
public interface JyDataUpdateService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "jyDataUpdate", targetNamespace = "http://service.ws.cxf.zytx.com/", className = "com.zytx.cxf.ws.client.JyDataUpdate")
    @ResponseWrapper(localName = "jyDataUpdateResponse", targetNamespace = "http://service.ws.cxf.zytx.com/", className = "com.zytx.cxf.ws.client.JyDataUpdateResponse")
    @WebMethod
    public java.lang.String jyDataUpdate(
        @WebParam(name = "xmlStr", targetNamespace = "")
        java.lang.String xmlStr
    );
}
