
/*
 * 
 */

package com.zytx.cxf.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Jul 03 15:40:08 CST 2017
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "JyDataAdd", 
                  wsdlLocation = "http://192.168.0.66:9014/JyDataAdd?wsdl",
                  targetNamespace = "http://service.ws.cxf.zytx.com/") 
public class JyDataAdd_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.ws.cxf.zytx.com/", "JyDataAdd");
    public final static QName JyDataAddServiceImpPort = new QName("http://service.ws.cxf.zytx.com/", "JyDataAddServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.66:9014/JyDataAdd?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://192.168.0.66:9014/JyDataAdd?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public JyDataAdd_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JyDataAdd_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JyDataAdd_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns JyDataAddService
     */
    @WebEndpoint(name = "JyDataAddServiceImpPort")
    public JyDataAddService getJyDataAddServiceImpPort() {
        return super.getPort(JyDataAddServiceImpPort, JyDataAddService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JyDataAddService
     */
    @WebEndpoint(name = "JyDataAddServiceImpPort")
    public JyDataAddService getJyDataAddServiceImpPort(WebServiceFeature... features) {
        return super.getPort(JyDataAddServiceImpPort, JyDataAddService.class, features);
    }

}
