
/*
 * 
 */

package com.zytx.cxf.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 20 17:39:45 CST 2017
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "JyDataUpdate", 
                  wsdlLocation = "http://119.6.254.76:9014/JyDataUpdate?wsdl",
                  targetNamespace = "http://service.ws.cxf.zytx.com/") 
public class JyDataUpdate_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.ws.cxf.zytx.com/", "JyDataUpdate");
    public final static QName JyDataUpdateServiceImpPort = new QName("http://service.ws.cxf.zytx.com/", "JyDataUpdateServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://119.6.254.76:9014/JyDataUpdate?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://119.6.254.76:9014/JyDataUpdate?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public JyDataUpdate_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JyDataUpdate_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JyDataUpdate_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns JyDataUpdateService
     */
    @WebEndpoint(name = "JyDataUpdateServiceImpPort")
    public JyDataUpdateService getJyDataUpdateServiceImpPort() {
        return super.getPort(JyDataUpdateServiceImpPort, JyDataUpdateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JyDataUpdateService
     */
    @WebEndpoint(name = "JyDataUpdateServiceImpPort")
    public JyDataUpdateService getJyDataUpdateServiceImpPort(WebServiceFeature... features) {
        return super.getPort(JyDataUpdateServiceImpPort, JyDataUpdateService.class, features);
    }

}
