
/*
 * 
 */

package com.zytx.cxf.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jul 12 17:03:58 CST 2017
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "tsDeviceService", 
                  wsdlLocation = "http://178.17.7.35:9090/cxfws/tsDeviceService?wsdl",
                  targetNamespace = "http://impl.device.ws.ts.zjpt/") 
public class TsDeviceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.device.ws.ts.zjpt/", "tsDeviceService");
    public final static QName TsDeivceServiceImplPort = new QName("http://impl.device.ws.ts.zjpt/", "TsDeivceServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://178.17.7.35:9090/cxfws/tsDeviceService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://178.17.7.35:9090/cxfws/tsDeviceService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TsDeviceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TsDeviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TsDeviceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns TsDeivceService
     */
    @WebEndpoint(name = "TsDeivceServiceImplPort")
    public TsDeivceService getTsDeivceServiceImplPort() {
        return super.getPort(TsDeivceServiceImplPort, TsDeivceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TsDeivceService
     */
    @WebEndpoint(name = "TsDeivceServiceImplPort")
    public TsDeivceService getTsDeivceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TsDeivceServiceImplPort, TsDeivceService.class, features);
    }

}
