package com.zytx.cxf.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jul 12 17:03:58 CST 2017
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://device.ws.ts.zjpt/", name = "TsDeivceService")
@XmlSeeAlso({ObjectFactory.class})
public interface TsDeivceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateQrCodeByRegCode", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateQrCodeByRegCode")
    @ResponseWrapper(localName = "updateQrCodeByRegCodeResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateQrCodeByRegCodeResponse")
    @WebMethod
    public java.lang.String updateQrCodeByRegCode(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "registrationCode", targetNamespace = "")
        java.lang.String registrationCode,
        @WebParam(name = "rqCode", targetNamespace = "")
        java.lang.String rqCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateParamInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateParamInfo")
    @ResponseWrapper(localName = "updateParamInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateParamInfoResponse")
    @WebMethod
    public java.lang.String updateParamInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertDeviceInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.InsertDeviceInfo")
    @ResponseWrapper(localName = "insertDeviceInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.InsertDeviceInfoResponse")
    @WebMethod
    public java.lang.String insertDeviceInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateQrCodeByQrCode", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateQrCodeByQrCode")
    @ResponseWrapper(localName = "updateQrCodeByQrCodeResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateQrCodeByQrCodeResponse")
    @WebMethod
    public java.lang.String updateQrCodeByQrCode(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "oldRqCode", targetNamespace = "")
        java.lang.String oldRqCode,
        @WebParam(name = "newRqCode", targetNamespace = "")
        java.lang.String newRqCode
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateMaintanInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateMaintanInfo")
    @ResponseWrapper(localName = "updateMaintanInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateMaintanInfoResponse")
    @WebMethod
    public java.lang.String updateMaintanInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "rqCode", targetNamespace = "")
        java.lang.String rqCode,
        @WebParam(name = "jsonString", targetNamespace = "")
        java.lang.String jsonString
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geDeviceInfoByRegCode", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.GeDeviceInfoByRegCode")
    @ResponseWrapper(localName = "geDeviceInfoByRegCodeResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.GeDeviceInfoByRegCodeResponse")
    @WebMethod
    public java.lang.String geDeviceInfoByRegCode(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "regCode", targetNamespace = "")
        java.lang.String regCode,
        @WebParam(name = "DeviceType", targetNamespace = "")
        java.lang.String deviceType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatDeviceInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdatDeviceInfo")
    @ResponseWrapper(localName = "updatDeviceInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdatDeviceInfoResponse")
    @WebMethod
    public java.lang.String updatDeviceInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geDeviceInfoByQrCode", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.GeDeviceInfoByQrCode")
    @ResponseWrapper(localName = "geDeviceInfoByQrCodeResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.GeDeviceInfoByQrCodeResponse")
    @WebMethod
    public java.lang.String geDeviceInfoByQrCode(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "QrCode", targetNamespace = "")
        java.lang.String qrCode,
        @WebParam(name = "DeviceType", targetNamespace = "")
        java.lang.String deviceType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDeviceStatus", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateDeviceStatus")
    @ResponseWrapper(localName = "updateDeviceStatusResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.zytx.cxf.ws.client.UpdateDeviceStatusResponse")
    @WebMethod
    public java.lang.String updateDeviceStatus(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "deviceStatus", targetNamespace = "")
        java.lang.String deviceStatus,
        @WebParam(name = "rqCode", targetNamespace = "")
        java.lang.String rqCode
    );
}
